---
- name: webservers
  hosts: webserver
  vars:
    web_pkg: httpd
    firewall_pkg: firewalld
    web_service: httpd
    firewall_service: firewalld
    python_pkg: wget
    rule: http
  become: yes
  tasks:

    - name: Ensure installed packages
      ansible.builtin.dnf:
        name: 
          - "{{ web_pkg }}"
          - "{{ firewall_pkg }}"
        state: present

    - name: Ensure httpd run
      ansible.builtin.service:
        name: "{{ web_service }}"
        state: started
        enabled: yes

    - name: Ensure firewall run
      ansible.builtin.service:
        name: "{{ firewall_service }}"
        state: started
        enabled: yes

    - name: Create index.html
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: "Example web content"
  
    - name: permit traffic
      ansible.builtin.firewalld:
        service: "{{ rule }}"
        permanent: true
        state: enabled
        immediate: yes

- name: Test webserver
  hosts: localhost
  tasks:

    - name: Test web
      ansible.builtin.uri:
        url: http://vm-1-node1-ansible
        method: GET
        status_code: 200
