---
- name: create user accounts for all our servers
  hosts: devservers
  become: true
  remote_user: student
  vars_files:
    - secret.yml
  tasks:
  - name: Creating user from secret.yml
    ansible.builtin.user:
      name: "{{ username }}"
      password: "{{ password }}"
      shell: /bin/bash
      state: present
