---
- hosts: all
  user: student
  become: true
  vars:
    system_owner: renecito@soporte.linux
  tasks:

    - name: Install template motd.j2
      ansible.builtin.template:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644

